In [4]:
import pandas as pd

data = {
    'Hours_Studied': [1, 2, 3, 4, 5, 6, 7, 8, 2.5, 3.5, 5.5, 6.5],
    'Attendance': [50, 60, 65, 70, 75, 80, 85, 90, 55, 68, 78, 88],
    'Marks': [35, 40, 45, 50, 55, 65, 70, 80, 42, 48, 60, 72]
} 

df=pd.DataFrame(data)
df

    Hours_Studied  Attendance  Marks
0             1.0          50     35
1             2.0          60     40
2             3.0          65     45
3             4.0          70     50
4             5.0          75     55
5             6.0          80     65
6             7.0          85     70
7             8.0          90     80
8             2.5          55     42
9             3.5          68     48
10            5.5          78     60
11            6.5          88     72

In [5]:
x=df[["Hours_Studied"]]
y=df["Marks"]

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
model=LinearRegression()

In [8]:
model.fit(x,y)

LinearRegression()

In [9]:


model.predict([[9]])

C:\Users\Nandini b m\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([84.33012821])

In [10]:
model.coef_

array([6.48076923])

In [11]:
model.intercept_

np.float64(26.003205128205124)

In [12]:
(6.48076923*9)+26.003205128205124

84.33012819820513

multiple linear regression

In [13]:
#feature selection
x=df[["Hours_Studied","Attendance"]]#input feature
y=df["Marks"]#output/target

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:

mlr=LinearRegression()

In [16]:
mlr.fit(x,y)

LinearRegression()

In [17]:
mlr.predict([[2,50]])

C:\Users\Nandini b m\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([38.03761946])

In [18]:
mlr.coef_

array([5.75038072, 0.1251407 ])

In [19]:
mlr.intercept_

np.float64(20.279822993224293)

In [20]:
(5.75038072*2)+(0.1251407*50)+20.279822993224293

38.03761943322429

In [21]:

x=df[["Hours_Studied","Attendance"]]#input feature
y=df["Marks"]#output/target

In [22]:
from sklearn.model_selection import train_test_split

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train

    Hours_Studied  Attendance
8             2.5          55
5             6.0          80
2             3.0          65
1             2.0          60
11            6.5          88
4             5.0          75
7             8.0          90
3             4.0          70
6             7.0          85

In [34]:
mlr1=LinearRegression().fit(x_train,y_train)

In [37]:
y_pred=mlr1.predict(x_test)
y_pred

array([61.85624547, 48.69893809, 30.96309207])

In [46]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [47]:
print("error",mean_squared_error(y_pred,y_test))
print("r2 score=",r2_score(y_pred,y_test))
print("MAE= ",mean_absolute_error(y_pred,y_test))

error 6.7435957672980615
r2 score= 0.957912790023541
MAE=  2.1973638291589452

In [1]:
#logistic regression
import pandas as pd
data={
   'Age':[25,40,35,50,23,45,52,33],
   'Balance':[20000,50000,30000,80000, 15000,60000,90000,40000],
   'Active':[1,0,1,0,1,0,0,1],
   'Churn':[0,1,0,1,0,1,1,0]
}
df=pd.DataFrame(data)
df

   Age  Balance  Active  Churn
0   25    20000       1      0
1   40    50000       0      1
2   35    30000       1      0
3   50    80000       0      1
4   23    15000       1      0
5   45    60000       0      1
6   52    90000       0      1
7   33    40000       1      0

In [4]:
x=df[['Age','Balance','Active',	]]
y=df['Churn']

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
from sklearn.linear_model import LogisticRegression

In [11]:
lr=LogisticRegression().fit(x_train,y_train)

C:\Users\Nandini b m\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [12]:
lr.predict([[25,1000,0]])

C:\Users\Nandini b m\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [13]:
lr.predict_proba([[25,10000,0]])

C:\Users\Nandini b m\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[1.00000000e+00, 6.39595881e-20]])

In [17]:
y_pred=lr.predict(x_test)

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [19]:
print("accuracy",accuracy_score(y_test,y_pred))
print("confusion_matric=\n",confusion_matrix(y_test,y_pred))
print("classification_report=",classification_report(y_test,y_pred))

accuracy 0.5
confusion_matric=
 [[0 0]
 [1 1]]
classification_report=               precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.50      0.67         2

    accuracy                           0.50         2
   macro avg       0.50      0.25      0.33         2
weighted avg       1.00      0.50      0.67         2

C:\Users\Nandini b m\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Nandini b m\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Nandini b m\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])